version: '3.8'

networks:
  iot-network:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - ./influxdb/.env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - iot-network

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto
    networks:
      - iot-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ufhb2025
    depends_on:
      - influxdb
    networks:
      - iot-network
